# Generated by Django 3.2.12 on 2022-03-22 03:40

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('college_rep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Authentication.useraccount')),
                ('num_of_boys', models.IntegerField()),
                ('num_of_girls', models.IntegerField()),
                ('num_of_officials', models.IntegerField()),
                ('leader_name', models.CharField(max_length=50)),
                ('leader_contact_num', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('game_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_name', models.CharField(max_length=40)),
                ('captain_phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(blank=True), blank=True, size=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teams.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
