# Generated by Django 3.2.12 on 2022-03-22 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20220322_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None),
        ),
    ]
