# Generated by Django 3.2.12 on 2023-08-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_alter_team_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent',
            name='num_of_officials',
        ),
        migrations.AddField(
            model_name='contingent',
            name='num_of_coaches_pti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='num_of_faculty_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contingent',
            name='num_of_supporting_staff',
            field=models.IntegerField(default=0),
        ),
    ]
