# Generated by Django 3.2.12 on 2023-09-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_auto_20230829_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
