# Generated by Django 3.2.12 on 2023-10-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20231007_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='made_new_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
