# Generated by Django 3.2.12 on 2023-10-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_auto_20231010_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='comments',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Verified')], default=0),
        ),
    ]
