# Generated by Django 3.2.12 on 2023-10-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0006_auto_20231011_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='made_new_changes',
        ),
    ]
